### PR TITLE
allow different charts from one tag via docxtemplater loop functionality

### PR DESCRIPTION
**Pull request by colmben**
Currently the chart module doesn't deal correctly with the loop functionality offered by the docxtemplater library. This is because the internal filename given to the chart is based on the tag name in the template and so in a loop it keeps overwriting the chart with the same filename. So you end up with the right number of charts in the output docx but they are all the same chart - the last chart in the loop. This one line fix just adds on a number to the tag when creating the internal filename. This allows for different charts to be produced inside the loop.

### CODE REVIEW

**Comment by dderg** [comment]
can you make tests pass?

**Comment by dderg** [comment]
i guess it will be enough if you change test expected files with correct ones

**Comment by colmben** [comment]
Hi,

I'll have a look at the tests later this evening.

Cheers,
Colm

**Comment by dderg** [comment]
Thanks a lot, merged

**Comment by dderg** [comment]
published to npm

**Pull request merged**
